---
- name: Install Kubernetes tools
  block:
    - name: Install kubectl and helm
      become: yes
      package:
        name:
          - helm
          - kubectl
        state: present
    - name: Install Lens
      become: yes
      become_user: aurbuilder
      aur:
        name: lens-bin
        use: "{{ aur_helper }}"
        state: present

- name: Install Terraform
  become: yes
  package:
    name: terraform
    state: present
