- when: ansible_distribution == 'Archlinux'
  include_tasks: arch.yml

- when: ansible_distribution == 'Fedora'
  include_tasks: fedora.yml

- name: Set ibus config
  dconf:
    key: "/desktop/ibus/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ ibus_config | dict2items }}"
