- name: Install development tools
  become: true
  pacman:
    name:
      - gimp
      - go
      - helm
      - k9s
      - kubectl
      - kustomize
      - python-pre-commit
      - rust
      - rust-src
      - terraform
      - terragrunt
    state: present

- name: Install development tools from the AUR
  kewlfft.aur.aur:
    name:
      - dive-bin
      - onlyoffice-bin
    state: present
