- name: Install Docker
  become: true
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - docker
    append: true

- name: Enable Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: true
