- name: Install tools
  become: true
  pacman:
    name:
      - ansible
      - aria2
      - btop
      - direnv
      - github-cli
      - jq
      - mpv
      - openssh
      - posix
      - translate-shell
      - tree
      - unrar
      - unzip
      - wireguard-tools
      - youtube-dl
      - zathura
      - zathura-pdf-mupdf
    state: present
