---

- name: Install packages
  become: yes
  package:
    name: "{{ essential_packages.official + extra_packages.official }}"
    state: present

- name: Create AUR builder user
  become: yes
  user:
    name: aurbuilder
    group: wheel

- name: Allow AUR builder user to use sudo without password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/aurbuilder
    line: "aurbuilder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"

- name: Install AUR helper ({{ aur_helper }})
  aur:
    name: "{{ aur_helper }}"
    use: makepkg
    state: present

- name: Install packages from AUR
  aur:
    name: "{{ essential_packages.aur + extra_packages.aur }}"
    use: "{{ aur_helper }}"
    state: present

- name: Install custom packages
  become: yes
  make:
    chdir: "{{ home }}/.local/src/{{ item }}"
    target: install
  with_items:
    - "{{ essential_packages.custom }}"

- name: Clean up after compiling custom packages
  become: yes
  make:
    chdir: "{{ home }}/.local/src/{{ item }}"
    target: clean
  with_items:
    - "{{ essential_packages.custom }}"

- name: Add user to video group for brightness control with the light package
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    group: "video"
    append: yes
