---

- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "{{ home }}"

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "{{ home }}"
    value: "no"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "{{ home }}"
  register: add_remote
  failed_when: add_remote.rc != 0 and "already exist" not in add_remote.stderr

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ home }}"
    update: yes
