- name: Install bluetooth
  become: true
  pacman:
    name:
      - blueman
      - bluez
      - bluez-utils

- name: Enable bluetooth service
  become: true
  systemd:
    name: bluetooth
    state: started
    enabled: true

# Connect to keyboard
# bluetoothctl power on
# bluetoothctl agent KeyboardOnly
# bluetoothctl default-agent
# bluetoothctl pairable on
# bluetoothctl scan on
# bluetoothctl pair C2:00:03:04:B2:BB
