---
- name: Ensure SSH configuration directory exists
  file:
    path: "{{ home }}/.ssh/"
    state: directory

- name: Generate SSH key
  openssh_keypair:
    path: "{{ home }}/.ssh/id_rsa"
    type: rsa
    size: 4096

- name: Add SSH public key to GitHub
  uri:
    url: https://api.github.com/user/keys
    method: POST
    body:
      title: "{{ ansible_hostname }}"
      key: "{{ lookup('file', '{{ home }}/.ssh/id_rsa.pub') }}"
    body_format: json
    headers:
      Authorization: "token {{ github_access_token }}"
    status_code:
      - 201
      - 422

- name: Always use SSH instead of HTTPS for GitHub repositories
  git_config:
    name: "url.git@github.com:.insteadOf"
    scope: global
    value: "https://github.com/"
