---
- name: Ensure SSH configuration directory exists
  file:
    path: "{{ home }}/.ssh/"
    state: directory

- name: Generate SSH key
  openssh_keypair:
    path: "{{ home }}/.ssh/id_rsa"
    type: rsa
    size: 4096
