- name: Ensure SSH configuration directory exists
  file:
    path: "~/.ssh/"
    state: directory

- name: Generate SSH key
  openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: ed25519
  register: ssh_key
