- name: Install interception tools
  become: true
  pacman:
    name:
      - interception-tools
      - interception-caps2esc

- name: Copy interception config
  become: true
  copy:
    src: udevmon.yaml
    dest: /etc/interception/udevmon.yaml

- name: Enable interception service
  become: true
  systemd:
    name: udevmon
    state: started
    enabled: true
