- name: Copy pacman config file
  become: true
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Install reflector
  become: true
  pacman:
    name: reflector
    state: present

- name: Copy reflector config file
  become: true
  copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf

- name: Enable reflector service
  become: true
  systemd:
    name: reflector
    enabled: true

- name: Upgrade packages
  become: true
  pacman:
    update_cache: true
    upgrade: true
