- name: Allow current user to install packages without password
  become: true
  lineinfile:
    dest: /etc/sudoers.d/pacman
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    state: present
    create: true
    validate: /usr/bin/visudo -cf %s
