---

- name: Install packages
  become: yes
  package:
    name: "{{ essential_packages.official + extra_packages.official }}"
    state: present

- name: Install AUR helper ({{ aur_helper }})
  aur:
    name: "{{ aur_helper }}"
    use: makepkg
    state: present

- name: Install packages from AUR
  aur:
    name: "{{ essential_packages.aur + extra_packages.aur }}"
    use: "{{ aur_helper }}"
    state: present

- name: Download custom packages source
  with_items: "{{ essential_packages.custom }}"
  git:
    repo: "https://github.com/khuedoan/{{ item }}.git"
    dest: "/tmp/{{ item }}"

- name: Install custom packages
  with_items: "{{ essential_packages.custom }}"
  become: yes
  make:
    chdir: "/tmp/{{ item }}"
    target: install

- name: Clean up custom package sources
  with_items: "{{ essential_packages.custom }}"
  become: yes
  file:
    path: "/tmp/{{ item }}"
    state: absent

- name: Add user to video group for brightness control with the light package
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    group: "video"
    append: yes
